import os, os.path, pandas as pd
from sqlalchemy import *

class geoindicators:
    engine = None
    initial_dataframe = None

    geoind_types = {
        "AH_AnnGrassCover" : NUMERIC(),
        "AH_ForbCover" : NUMERIC(),
        "AH_GrassCover" : NUMERIC(),
        "AH_NonNoxAnnForbCover" : NUMERIC(),
        "AH_NonNoxAnnForbGrassCover" : NUMERIC(),
        "AH_NonNoxAnnGrassCover" : NUMERIC(),
        "AH_NonNoxCover" : NUMERIC(),
        "AH_NonNoxPerenForbCover" : NUMERIC(),
        "AH_NonNoxPerenForbGrassCover" : NUMERIC(),
        "AH_NonNoxPerenGrassCover" : NUMERIC(),
        "AH_NonNoxShrubCover" : NUMERIC(),
        "AH_NonNoxSubShrubCover" : NUMERIC(),
        "AH_NonNoxSucculentCover" : NUMERIC(),
        "AH_NonNoxTreeCover" : NUMERIC(),
        "AH_NonSagebrushShrubCover" : NUMERIC(),
        "AH_NoxAnnForbCover" : NUMERIC(),
        "AH_NoxAnnForbGrassCover" : NUMERIC(),
        "AH_NoxAnnGrassCover" : NUMERIC(),
        "AH_NoxCover" : NUMERIC(),
        "AH_NoxPerenForbCover" : NUMERIC(),
        "AH_NoxPerenForbGrassCover" : NUMERIC(),
        "AH_NoxPerenGrassCover" : NUMERIC(),
        "AH_NoxShrubCover" : NUMERIC(),
        "AH_NoxSubShrubCover" : NUMERIC(),
        "AH_NoxSucculentCover" : INTEGER(),
        "AH_NoxTreeCover" : NUMERIC(),
        "AH_PerenForbCover" : NUMERIC(),
        "AH_PerenGrassCover" : NUMERIC(),
        "AH_PerenGrassForbCover" : NUMERIC(),
        "AH_PreferredForb" : NUMERIC(),
        "AH_PreferredForbCover" : NUMERIC(),
        "AH_SagebrushCover" : NUMERIC(),
        "AH_SagebrushCover_Live" : NUMERIC(),
        "AH_ShortPerenGrassCover" : NUMERIC(),
        "AH_ShrubCover" : NUMERIC(),
        "AH_TallPerenGrassCover" : NUMERIC(),
        "BareSoilCover" : NUMERIC(),
        "County" : TEXT(),
        "DBKey" : TEXT(),
        "DateEstablished" : DATE(),
        "DateLoadedInDb" : TEXT(),
        "DateVisited" : DATE(),
        "ELEVATION" : NUMERIC(),
        "EcolSiteName" : TEXT(),
        "EcologicalSiteId" : TEXT(),
        "FH_CyanobacteriaCover" : NUMERIC(),
        "FH_DepSoilCover" : NUMERIC(),
        "FH_DuffCover" : NUMERIC(),
        "FH_EmbLitterCover" : NUMERIC(),
        "FH_HerbLitterCover" : NUMERIC(),
        "FH_LichenCover" : NUMERIC(),
        "FH_MossCover" : NUMERIC(),
        "FH_NonNoxAnnForbCover" : NUMERIC(),
        "FH_NonNoxAnnGrassCover" : NUMERIC(),
        "FH_NonNoxPerenForbCover" : NUMERIC(),
        "FH_NonNoxPerenGrassCover" : NUMERIC(),
        "FH_NonNoxShrubCover" : NUMERIC(),
        "FH_NonNoxSubShrubCover" : NUMERIC(),
        "FH_NonNoxSucculentCover" : NUMERIC(),
        "FH_NonNoxTreeCover" : NUMERIC(),
        "FH_NoxAnnForbCover" : NUMERIC(),
        "FH_NoxAnnGrassCover" : NUMERIC(),
        "FH_NoxPerenForbCover" : NUMERIC(),
        "FH_NoxPerenGrassCover" : NUMERIC(),
        "FH_NoxShrubCover" : NUMERIC(),
        "FH_NoxSubShrubCover" : NUMERIC(),
        "FH_NoxSucculentCover" : INTEGER(),
        "FH_NoxTreeCover" : NUMERIC(),
        "FH_RockCover" : NUMERIC(),
        "FH_SagebrushCover" : NUMERIC(),
        "FH_TotalLitterCover" : NUMERIC(),
        "FH_VagrLichenCover" : NUMERIC(),
        "FH_WaterCover" : NUMERIC(),
        "FH_WoodyLitterCover" : NUMERIC(),
        "GapCover_101_200" : NUMERIC(),
        "GapCover_200_plus" : NUMERIC(),
        "GapCover_25_50" : NUMERIC(),
        "GapCover_25_plus" : NUMERIC(),
        "GapCover_51_100" : NUMERIC(),
        "GlobalID" : TEXT(),
        "Hgt_Forb_Avg" : NUMERIC(),
        "Hgt_Grass_Avg" : NUMERIC(),
        "Hgt_Herbaceous_Avg" : NUMERIC(),
        "Hgt_NonNoxPerenGrass_Avg" : NUMERIC(),
        "Hgt_NonSagebrushShrub_Avg" : NUMERIC(),
        "Hgt_NoxPerenGrass_Avg" : NUMERIC(),
        "Hgt_PerenForbGrass_Avg" : NUMERIC(),
        "Hgt_PerenForb_Avg" : NUMERIC(),
        "Hgt_PerenGrass_Avg" : NUMERIC(),
        "Hgt_Sagebrush_Avg" : NUMERIC(),
        "Hgt_Sagebrush_Live_Avg" : NUMERIC(),
        "Hgt_ShortPerenGrass_Avg" : NUMERIC(),
        "Hgt_TallPerenGrass_Avg" : NUMERIC(),
        "Hgt_Woody_Avg" : NUMERIC(),
        "latitude_nad83" : NUMERIC(),
        "LocationType" : TEXT(),
        "Longitude_NAD83" : NUMERIC(),
        "NumSpp_NonNoxPlant" : NUMERIC(),
        "NumSpp_NoxPlant" : NUMERIC(),
        "NumSpp_PreferredForb" : NUMERIC(),
        "PLOTKEY" : TEXT(),
        "PercentCoveredByEcoSite" : NUMERIC(),
        "PlotID" : TEXT(),
        "plotkey2" : NUMERIC(),
        "PrimaryKey" : VARCHAR(100),
        "ProjectName" : TEXT(),
        "RH_AnnualProd" : TEXT(),
        "RH_BareGround" : TEXT(),
        "RH_BioticIntegrity" : TEXT(),
        "RH_CommentsBI" : TEXT(),
        "RH_CommentsHF" : TEXT(),
        "RH_CommentsSS" : TEXT(),
        "RH_Compaction" : TEXT(),
        "RH_DeadDyingPlantParts" : TEXT(),
        "RH_FuncSructGroup" : TEXT(),
        "RH_Gullies" : TEXT(),
        "RH_HydrologicFunction" : TEXT(),
        "RH_InvasivePlants" : TEXT(),
        "RH_LitterAmount" : TEXT(),
        "RH_LitterMovement" : TEXT(),
        "RH_PedestalsTerracettes" : TEXT(),
        "RH_PlantCommunityComp" : TEXT(),
        "RH_ReprodCapabilityPeren" : TEXT(),
        "RH_Rills" : TEXT(),
        "RH_SoilSiteStability" : TEXT(),
        "RH_SoilSurfLossDeg" : TEXT(),
        "RH_SoilSurfResisErosion" : TEXT(),
        "RH_WaterFlowPatterns" : TEXT(),
        "RH_WindScouredAreas" : TEXT(),
        "RecordCount" : TEXT(),
        "SagebrushShape_All_ColumnCount" : NUMERIC(),
        "SagebrushShape_All_Predominant" : TEXT(),
        "SagebrushShape_All_SpreadCount" : NUMERIC(),
        "SagebrushShape_Live_ColumnCount" : NUMERIC(),
        "SagebrushShape_Live_Predominant" : TEXT(),
        "SagebrushShape_Live_SpreadCount" : NUMERIC(),
        "SoilStability_All" : NUMERIC(),
        "SoilStability_Protected" : NUMERIC(),
        "SoilStability_Unprotected" : NUMERIC(),
        "Spp_Nox" : TEXT(),
        "Spp_PreferredForb" : TEXT(),
        "Spp_Sagebrush" : TEXT(),
        "Spp_ShortPerenGrass" : TEXT(),
        "Spp_TallPerenGrass" : TEXT(),
        "State" : TEXT(),
        "TotalFoliarCover" : NUMERIC(),
        "created_date" : DATE(),
        "created_user" : TEXT(),
        "last_edited_date" : DATE(),
        "last_edited_user" : TEXT()
        }

    def __init__(self,path):

        """ clearing attributes & setting engine """
        self.engine = create_engine(os.environ.get('DBSTR'))
        self.initial_dataframe = None
        self.geo_dataframe = None

        """ prepping a geodf from path """
        self.initial_dataframe = pd.read_csv(path, low_memory=False)


    def send_to_pg(self):

        self.initial_dataframe.to_sql('geoIndicators', self.engine, index=False, dtype=self.geoind_types)
